/**
 * 跨岗位通用技能词库（中英文别名，命中任一即可）。
 * 用于 JD 解析阶段识别岗位专业能力要求，并在简历中比对覆盖情况。
 * 注意：词库覆盖只作为「技能出现」的弱证据，不能单独决定评分，
 * 评分必须结合行为证据（主导角色 / 量化结果 / 落地交付）。
 */
export interface SkillSignal {
  aliases: string[]
  label: string
}

export const SKILL_LEXICON: SkillSignal[] = [
  // —— 技术研发 ——
  { aliases: ['python'], label: 'Python' },
  { aliases: ['c++'], label: 'C++' },
  { aliases: ['java'], label: 'Java' },
  { aliases: ['golang', 'go 语言'], label: 'Go' },
  { aliases: ['pytorch'], label: 'PyTorch' },
  { aliases: ['tensorflow'], label: 'TensorFlow' },
  { aliases: ['transformer'], label: 'Transformer' },
  { aliases: ['bert', 'roberta'], label: 'BERT 系预训练模型' },
  { aliases: ['gpt', 'llama', 'qwen', 'chatglm', 'deepseek'], label: '主流大模型' },
  { aliases: ['llm', '大模型', '大语言模型'], label: '大模型（LLM）' },
  { aliases: ['nlp', '自然语言处理'], label: '自然语言处理（NLP）' },
  { aliases: ['rag', '检索增强'], label: 'RAG 检索增强' },
  { aliases: ['langchain'], label: 'LangChain' },
  { aliases: ['milvus', 'faiss', '向量数据库'], label: '向量数据库' },
  { aliases: ['sft', 'fine-tun', '微调'], label: '模型微调（SFT）' },
  { aliases: ['lora', 'qlora'], label: 'LoRA 参数高效微调' },
  { aliases: ['vllm', 'tensorrt', 'onnx', '推理部署', '模型服务化'], label: '推理加速与部署' },
  { aliases: ['agent', '智能体'], label: 'Agent 智能体' },
  { aliases: ['多模态'], label: '多模态' },
  { aliases: ['意图识别'], label: '意图识别' },
  { aliases: ['命名实体', 'ner'], label: '命名实体识别（NER）' },
  { aliases: ['文本分类'], label: '文本分类' },
  { aliases: ['语义匹配'], label: '语义匹配' },
  { aliases: ['prompt', '提示词'], label: 'Prompt 工程' },
  { aliases: ['huggingface'], label: 'HuggingFace 生态' },
  { aliases: ['deepspeed'], label: 'DeepSpeed 分布式训练' },
  { aliases: ['docker'], label: 'Docker' },
  { aliases: ['kubernetes', 'k8s'], label: 'Kubernetes' },
  { aliases: ['spark', 'flink', 'kafka'], label: '大数据计算' },
  { aliases: ['前端', 'react', 'vue', 'typescript'], label: '前端开发' },
  { aliases: ['后端', '微服务', 'spring'], label: '后端开发' },
  { aliases: ['测试', '自动化测试', 'qa'], label: '测试与质量保障' },
  { aliases: ['运维', 'devops', 'ci/cd'], label: '运维与 DevOps' },
  // —— 产品 ——
  { aliases: ['需求分析', '需求评审', '需求管理'], label: '需求分析与管理' },
  { aliases: ['prd', '产品文档'], label: 'PRD 撰写' },
  { aliases: ['产品规划', '路线图', 'roadmap'], label: '产品规划' },
  { aliases: ['axure'], label: 'Axure 原型' },
  { aliases: ['figma'], label: 'Figma' },
  { aliases: ['用户调研', '用户访谈', '深度访谈'], label: '用户调研' },
  { aliases: ['竞品分析'], label: '竞品分析' },
  { aliases: ['用户画像', 'persona'], label: '用户画像' },
  { aliases: ['a/b', 'ab 测试', 'ab测试', '对照实验'], label: 'A/B 实验' },
  { aliases: ['北极星', '指标体系', '指标拆解'], label: '指标体系搭建' },
  { aliases: ['saas'], label: 'SaaS 产品经验' },
  { aliases: ['b 端', 'b端'], label: 'B 端产品' },
  { aliases: ['c 端', 'c端'], label: 'C 端产品' },
  { aliases: ['产品经理', '产品策划'], label: '产品策划' },
  // —— 运营/市场 ——
  { aliases: ['用户运营'], label: '用户运营' },
  { aliases: ['内容运营'], label: '内容运营' },
  { aliases: ['活动运营', '活动策划'], label: '活动运营' },
  { aliases: ['社群运营', '社群'], label: '社群运营' },
  { aliases: ['私域'], label: '私域运营' },
  { aliases: ['新媒体运营', '新媒体'], label: '新媒体运营' },
  { aliases: ['电商运营'], label: '电商运营' },
  { aliases: ['增长黑客', '增长运营', '用户增长'], label: '增长运营' },
  { aliases: ['拉新', '获客'], label: '拉新获客' },
  { aliases: ['促活', '留存', '召回'], label: '促活与留存' },
  { aliases: ['转化', '转化率'], label: '转化运营' },
  { aliases: ['gmv'], label: 'GMV 经营' },
  { aliases: ['dau', 'mau'], label: 'DAU/MAU 运营' },
  { aliases: ['roi'], label: 'ROI 管理' },
  { aliases: ['投放', '信息流', 'sem'], label: '付费投放' },
  { aliases: ['裂变'], label: '裂变玩法' },
  { aliases: ['sop'], label: '运营 SOP' },
  { aliases: ['rfm', 'aarrr'], label: '用户分层模型（RFM/AARRR）' },
  { aliases: ['公众号'], label: '公众号运营' },
  { aliases: ['小红书'], label: '小红书运营' },
  { aliases: ['抖音', '短视频'], label: '抖音/短视频' },
  { aliases: ['视频号'], label: '视频号运营' },
  { aliases: ['直播'], label: '直播运营' },
  { aliases: ['文案', '选题'], label: '文案撰写' },
  { aliases: ['kol', '达人'], label: 'KOL/达人合作' },
  { aliases: ['会员运营', '复购'], label: '会员与复购运营' },
  { aliases: ['scrm', '企业微信'], label: '企业微信 SCRM' },
  { aliases: ['品牌'], label: '品牌营销' },
  { aliases: ['公关', '舆情'], label: '公关传播' },
  { aliases: ['seo'], label: 'SEO' },
  { aliases: ['渠道'], label: '渠道管理' },
  { aliases: ['商务拓展', 'bd'], label: '商务拓展（BD）' },
  { aliases: ['大客户', 'ka '], label: '大客户销售' },
  { aliases: ['mql', '销售线索', '线索'], label: '销售线索运营' },
  { aliases: ['白皮书'], label: '白皮书/案例营销' },
  { aliases: ['峰会', '展会', '行业活动'], label: '线下活动营销' },
  { aliases: ['提案', '宣讲'], label: '客户提案宣讲' },
  { aliases: ['谈判'], label: '商务谈判' },
  { aliases: ['客户成功'], label: '客户成功' },
  // —— HR ——
  { aliases: ['招聘'], label: '招聘配置' },
  { aliases: ['培训'], label: '培训发展' },
  { aliases: ['绩效'], label: '绩效管理' },
  { aliases: ['薪酬'], label: '薪酬福利' },
  { aliases: ['hrbp'], label: 'HRBP' },
  { aliases: ['组织发展', 'od '], label: '组织发展（OD）' },
  { aliases: ['员工关系'], label: '员工关系' },
  { aliases: ['人才盘点'], label: '人才盘点' },
  { aliases: ['雇主品牌'], label: '雇主品牌' },
  { aliases: ['劳动法'], label: '劳动法规' },
  { aliases: ['猎头'], label: '猎头渠道管理' },
  { aliases: ['内推'], label: '内推体系' },
  { aliases: ['任职资格'], label: '任职资格体系' },
  { aliases: ['胜任力模型', '胜任力'], label: '胜任力建模' },
  { aliases: ['三支柱'], label: 'HR 三支柱' },
  { aliases: ['校招'], label: '校园招聘' },
  { aliases: ['人才测评', '测评'], label: '人才测评' },
  { aliases: ['okr'], label: 'OKR 管理' },
  { aliases: ['敬业度'], label: '员工敬业度' },
  // —— 设计 ——
  { aliases: ['ui 设计', 'ui设计'], label: 'UI 设计' },
  { aliases: ['ux', '用户体验设计'], label: 'UX 用户体验设计' },
  { aliases: ['交互设计'], label: '交互设计' },
  { aliases: ['视觉设计'], label: '视觉设计' },
  { aliases: ['平面设计'], label: '平面设计' },
  { aliases: ['设计系统', '组件库', 'design token'], label: '设计系统/组件库' },
  { aliases: ['可用性测试'], label: '可用性测试' },
  { aliases: ['信息架构'], label: '信息架构' },
  { aliases: ['作品集'], label: '作品集' },
  { aliases: ['动效', 'after effects'], label: '动效设计' },
  { aliases: ['photoshop'], label: 'Photoshop' },
  { aliases: ['illustrator'], label: 'Illustrator' },
  { aliases: ['sketch'], label: 'Sketch' },
  { aliases: ['还原度'], label: '设计还原走查' },
  // —— 通用职能/数据/协作工具 ——
  { aliases: ['项目管理', 'pmo'], label: '项目管理' },
  { aliases: ['pmp'], label: 'PMP 认证' },
  { aliases: ['sql'], label: 'SQL 数据分析' },
  { aliases: ['excel', '数据透视'], label: 'Excel 数据处理' },
  { aliases: ['tableau', 'power bi', '帆软'], label: 'BI 报表工具' },
  { aliases: ['ppt', 'powerpoint'], label: 'PPT 汇报' },
  { aliases: ['供应商管理', '供应商'], label: '供应商管理' },
  { aliases: ['合同'], label: '合同管理' },
  { aliases: ['预算管理', '预算'], label: '预算管理' },
  { aliases: ['风险'], label: '风险管理' },
  { aliases: ['erp'], label: 'ERP 系统' },
  { aliases: ['行政'], label: '行政管理' },
  { aliases: ['财务'], label: '财务专业' },
  { aliases: ['法务', '法律'], label: '法务合规' },
  { aliases: ['供应链'], label: '供应链管理' },
  { aliases: ['客户服务', '客服'], label: '客户服务' },
]

/** 行业词库：用于 Role Fit 中的行业相关性判断 */
export const INDUSTRY_WORDS = [
  '互联网', '电商', '电子商务', '金融', '银行', '保险', '证券', '教育', '医疗',
  '医药', '游戏', '汽车', '消费品', '零售', 'saas', '企业服务', '人工智能',
  '新能源', '智能制造', '制造业', '物流', '文旅', '房地产', '通信', '政企',
]
